# Generated by Django 4.2.20 on 2025-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_alter_drugcompatibility_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodanalysis',
            options={},
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS core_drug_name;",
            reverse_sql="CREATE UNIQUE INDEX core_drug_name ON core_drug(name);"
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255),
        )
    ]
