# Generated by Django 4.2.20 on 2025-05-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bloodanalysis_options_alter_drug_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='intakeduration',
            name='max_ge_rec_duration',
        )
    ]
