# Generated by Django 4.2.20 on 2025-05-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drop_intakeduration_max_ge_rec'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='druginfo',
            name='elimination_ge_half_life',
        )
    ]
