# Generated by Django 4.2.20 on 2025-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_elimination_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='decayformula',
            name='life_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        )
    ]
