# Generated by Django 4.2.20 on 2025-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_drugcompatibility_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='concentration_cache',
            field=models.JSONField(blank=True, help_text='{ drug_id: [{time,conc},…], … }', null=True),
        ),
    ]
