# Generated by Django 4.2.20 on 2025-05-03 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_concentration_cache_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedose',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='dose_clock',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='dose_mg',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='interval_d',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='interval_h',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='interval_w',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='coursedrugschedule',
            name='weekday',
        ),
        migrations.AddField(
            model_name='course',
            name='T_total',
            field=models.PositiveIntegerField(default=1680, help_text='Длительность приёма в часах'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_params',
            field=models.JSONField(default=dict, help_text='Параметры расписания (delta_t, day_of_week и т.д.)'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время начала курса (по умолчанию — текущее)'),
        ),
        migrations.AddField(
            model_name='coursedose',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Связь на шаблон приёма; временно может быть NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='core.coursedrugschedule'),
        ),
        migrations.AddField(
            model_name='coursedrugschedule',
            name='D',
            field=models.FloatField(blank=True, default=0.0, help_text='Доза в мг', null=True),
        ),
        migrations.AddField(
            model_name='coursedrugschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='coursedrugschedule',
            name='delta_t',
            field=models.FloatField(blank=True, help_text='Частота в часах', null=True),
        ),
        migrations.AddField(
            model_name='coursedrugschedule',
            name='dose_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Время дозы (по умолчанию 08:00)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='concentration_cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание курса (опционально)'),
        ),
        migrations.AlterField(
            model_name='coursedose',
            name='dose_mg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coursedrugschedule',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.drug'),
        ),
        migrations.AlterUniqueTogether(
            name='drugcompatibility',
            unique_together={('drug_a', 'drug_b')},
        ),
        migrations.RemoveField(
            model_name='coursedose',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedose',
            name='drug',
        ),
    ]
