# Generated by Django 4.2.20 on 2025-05-04 06:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_coursedose_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule_params',
            field=models.JSONField(blank=True, default=dict, help_text='Параметры расписания (delta_t, day_of_week и т.д.)'),
        ),
        migrations.AlterField(
            model_name='coursedrugschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='День недели (если приём 1 раз в неделю)', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='decayformula',
            name='life_hours',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='coursedose',
            unique_together={('schedule', 'intake_dt')},
        ),
        migrations.CreateModel(
            name='HistoricalCourseDrugSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('D', models.FloatField(blank=True, default=0.0, help_text='Доза в мг', null=True)),
                ('delta_t', models.FloatField(blank=True, help_text='Частота в часах', null=True)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='День недели (если приём 1 раз в неделю)', max_length=9, null=True)),
                ('dose_time', models.TimeField(default=datetime.time(8, 0), help_text='Время дозы (по умолчанию 08:00)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.course')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.drug')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course drug schedule',
                'verbose_name_plural': 'historical course drug schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCourseDose',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('intake_dt', models.DateTimeField()),
                ('dose_mg', models.FloatField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, db_constraint=False, help_text='Связь на шаблон приёма; временно может быть NULL', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coursedrugschedule')),
            ],
            options={
                'verbose_name': 'historical course dose',
                'verbose_name_plural': 'historical course doses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Описание курса (опционально)')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Время начала курса (по умолчанию — текущее)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('T_total', models.PositiveIntegerField(default=1680, help_text='Длительность приёма в часах')),
                ('schedule_params', models.JSONField(blank=True, default=dict, help_text='Параметры расписания (delta_t, day_of_week и т.д.)')),
                ('concentration_cache', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course',
                'verbose_name_plural': 'historical courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
